"""Initial migration

Revision ID: f9e173a047a0
Revises:
Create Date: 2026-06-06 21:08:39.706954

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f9e173a047a0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
